version: "2.1"
services:
  nginx:
    container_name: nginx-test-laravel
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./laravel:/var/www/html"
    links:
      - php
      - mysql
  php:
    container_name: php-test-laravel
    build: ./docker/php
    ports:
      - "3000:3000"
    volumes:
      - "./laravel:/var/www/html"
      - "~/.ssh:/root/.ssh"
    working_dir: "/var/www/html"
  mysql:
    container_name: mysql-test-laravel
    build: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=password
    volumes:
      - "./databases:/var/lib/mysql"